package vistas;

import controladores.AutorController;
import controladores.CancionController;
import db.ConexionDB4O;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Autor;
import modelos.Cancion;
import modelos.GeneroMusical;

/**
 *
 * @author ANDRÉS SAMUEL PODADERA GONZÁLEZ
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        this.inicializarFormulario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuAutores = new javax.swing.JPopupMenu();
        jMenuItemModificarAutor = new javax.swing.JMenuItem();
        jMenuItemEliminarAutor = new javax.swing.JMenuItem();
        jPopupMenuCanciones = new javax.swing.JPopupMenu();
        jMenuItemModificarCancion = new javax.swing.JMenuItem();
        jMenuItemEliminarCancion = new javax.swing.JMenuItem();
        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jPanelAutores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonGuardarAutor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutores = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPorcentajeAumento = new javax.swing.JTextField();
        jButtonAumentarSalario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSalarioInicial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSalarioFinal = new javax.swing.JTextField();
        jButtonConsultarAutoresEnRango = new javax.swing.JButton();
        jButtonConsultarAutoresEnRango1 = new javax.swing.JButton();
        jSpinnerAnyoNacimiento = new javax.swing.JSpinner();
        jSpinnerIngresosAnuales = new javax.swing.JSpinner();
        jPanelCanciones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jSpinnerDuracion = new javax.swing.JSpinner();
        jSpinnerAnyoCreacion = new javax.swing.JSpinner();
        jButtonGuardarCancion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCanciones = new javax.swing.JTable();
        jButtonConsultarCancionesOrdenadas = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBusquedaAutor = new javax.swing.JTextField();
        jButtonConsultarCancionesDeAutor = new javax.swing.JButton();
        jButtonConsultarTodasCanciones = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxAutores = new javax.swing.JComboBox<>();

        jMenuItemModificarAutor.setText("Modificar");
        jMenuItemModificarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemModificarAutorMousePressed(evt);
            }
        });
        jPopupMenuAutores.add(jMenuItemModificarAutor);

        jMenuItemEliminarAutor.setText("Eliminar");
        jMenuItemEliminarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemEliminarAutorMousePressed(evt);
            }
        });
        jPopupMenuAutores.add(jMenuItemEliminarAutor);

        jMenuItemModificarCancion.setText("Modificar");
        jMenuItemModificarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemModificarCancionMousePressed(evt);
            }
        });
        jPopupMenuCanciones.add(jMenuItemModificarCancion);

        jMenuItemEliminarCancion.setText("Eliminar");
        jMenuItemEliminarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemEliminarCancionMousePressed(evt);
            }
        });
        jPopupMenuCanciones.add(jMenuItemEliminarCancion);

        jPopupMenuCanciones.getAccessibleContext().setAccessibleParent(jTableCanciones);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Podadera's Songs Vault");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonSalir.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelAutores.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Autores");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nacionalidad:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("País:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Año Nacimiento:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ingresos Anuales:");

        jButtonGuardarAutor.setBackground(new java.awt.Color(102, 255, 102));
        jButtonGuardarAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardarAutor.setText("Guardar Autor");
        jButtonGuardarAutor.setBorder(null);
        jButtonGuardarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarAutorActionPerformed(evt);
            }
        });

        jTableAutores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Nacionalidad", "País", "Año Nacimiento", "Ingresos Anuales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAutores.setComponentPopupMenu(jPopupMenuAutores);
        jScrollPane1.setViewportView(jTableAutores);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Porcentaje de Aumento de sueldo:");

        jButtonAumentarSalario.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAumentarSalario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAumentarSalario.setText("Aumentar");
        jButtonAumentarSalario.setBorder(null);
        jButtonAumentarSalario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAumentarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentarSalarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Consultar autores con salario entre:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("y");

        jButtonConsultarAutoresEnRango.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConsultarAutoresEnRango.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarAutoresEnRango.setText("Consultar");
        jButtonConsultarAutoresEnRango.setBorder(null);
        jButtonConsultarAutoresEnRango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultarAutoresEnRango.setMaximumSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango.setMinimumSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango.setPreferredSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarAutoresEnRangoActionPerformed(evt);
            }
        });

        jButtonConsultarAutoresEnRango1.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConsultarAutoresEnRango1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarAutoresEnRango1.setText("Consultar Todos Autores");
        jButtonConsultarAutoresEnRango1.setBorder(null);
        jButtonConsultarAutoresEnRango1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultarAutoresEnRango1.setMaximumSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango1.setMinimumSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango1.setPreferredSize(new java.awt.Dimension(87, 23));
        jButtonConsultarAutoresEnRango1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarAutoresEnRango1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAutoresLayout = new javax.swing.GroupLayout(jPanelAutores);
        jPanelAutores.setLayout(jPanelAutoresLayout);
        jPanelAutoresLayout.setHorizontalGroup(
            jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonConsultarAutoresEnRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addComponent(jTextFieldSalarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultarAutoresEnRango, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addComponent(jTextFieldPorcentajeAumento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAumentarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAutoresLayout.createSequentialGroup()
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAutoresLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonGuardarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAnyoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerIngresosAnuales)))))
                .addGap(25, 25, 25))
        );
        jPanelAutoresLayout.setVerticalGroup(
            jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerAnyoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIngresosAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultarAutoresEnRango, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSalarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAumentarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPorcentajeAumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonConsultarAutoresEnRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanelCanciones.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Canciones");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Título:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Duración:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Año de creación:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Género:");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasica", "Jazz", "Reggaeton", "Rap", "Pop", "Electronica", "Indie" }));

        jButtonGuardarCancion.setBackground(new java.awt.Color(102, 255, 102));
        jButtonGuardarCancion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardarCancion.setText("Guardar Canción");
        jButtonGuardarCancion.setBorder(null);
        jButtonGuardarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCancionActionPerformed(evt);
            }
        });

        jTableCanciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Título", "Duración", "Año de creación", "Género", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCanciones.setComponentPopupMenu(jPopupMenuCanciones);
        jScrollPane2.setViewportView(jTableCanciones);

        jButtonConsultarCancionesOrdenadas.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConsultarCancionesOrdenadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarCancionesOrdenadas.setText("Consultar Canciones Ordenadas Por Título");
        jButtonConsultarCancionesOrdenadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Autor:");

        jButtonConsultarCancionesDeAutor.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConsultarCancionesDeAutor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarCancionesDeAutor.setText("Consultar canciones");
        jButtonConsultarCancionesDeAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonConsultarTodasCanciones.setBackground(new java.awt.Color(102, 255, 102));
        jButtonConsultarTodasCanciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarTodasCanciones.setText("Consultar Todas Canciones");
        jButtonConsultarTodasCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultarTodasCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTodasCancionesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Autor:");

        jComboBoxAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelCancionesLayout = new javax.swing.GroupLayout(jPanelCanciones);
        jPanelCanciones.setLayout(jPanelCancionesLayout);
        jPanelCancionesLayout.setHorizontalGroup(
            jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancionesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancionesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAnyoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)
                        .addComponent(jButtonGuardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancionesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonConsultarTodasCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConsultarCancionesOrdenadas)
                .addGap(82, 82, 82)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBusquedaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarCancionesDeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanelCancionesLayout.setVerticalGroup(
            jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jSpinnerAnyoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jComboBoxAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonGuardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarTodasCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarCancionesOrdenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldBusquedaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarCancionesDeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAumentarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentarSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAumentarSalarioActionPerformed

    private void jButtonConsultarAutoresEnRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarAutoresEnRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarAutoresEnRangoActionPerformed

    private void jButtonConsultarAutoresEnRango1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarAutoresEnRango1ActionPerformed
        // TODO add your handling code here:
        this.listarAutores();
    }//GEN-LAST:event_jButtonConsultarAutoresEnRango1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        ConexionDB4O.cerrar();
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonConsultarTodasCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTodasCancionesActionPerformed
        // TODO add your handling code here:
        this.listarCanciones();
    }//GEN-LAST:event_jButtonConsultarTodasCancionesActionPerformed

    private void jMenuItemEliminarCancionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemEliminarCancionMousePressed
        if (hayCancionSeleccionada()) {
            int filaSeleccionada = jTableCanciones.getSelectedRow();

            DefaultTableModel modelo = (DefaultTableModel) jTableCanciones.getModel();
            String idCancion = modelo.getValueAt(filaSeleccionada, 0).toString(); // Obtener el ID de la canción

            boolean resultado = CancionController.eliminar(idCancion);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "Canción eliminada correctamente de la base de datos DB4O", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "La canción seleccionada no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.listarCanciones();
        } else {
            JOptionPane.showMessageDialog(this, "Primero, debes seleccionar una canción", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemEliminarCancionMousePressed

    private void jButtonGuardarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarAutorActionPerformed
        String nombre = this.jTextFieldNombre.getText();
        String nacionalidad = this.jTextFieldNacionalidad.getText();
        String paisResidencia = this.jTextFieldPais.getText();
        int anyoNacimiento = Integer.parseInt(this.jSpinnerAnyoNacimiento.getValue().toString());
        int ingresosAnuales = Integer.parseInt(this.jSpinnerIngresosAnuales.getValue().toString());

        if (!nombre.isEmpty() && !nacionalidad.isEmpty() && !paisResidencia.isEmpty() && anyoNacimiento > 0 && ingresosAnuales > 0) {

            Autor nuevoAutor = new Autor(nombre, nacionalidad, paisResidencia, anyoNacimiento, ingresosAnuales);

            boolean resultado = AutorController.guardar(nuevoAutor);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "Autor almacenado correctamente en la base de datos DB4O", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            this.limpiarFormularioAutor();
            this.listarAutores();
        } else {
            JOptionPane.showMessageDialog(null, "Revisa la información introducida para almacenar el autor", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarAutorActionPerformed

    private void jButtonGuardarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCancionActionPerformed
        String titulo = this.jTextFieldTitulo.getText();
        int duracion = Integer.parseInt(this.jSpinnerDuracion.getValue().toString());
        int anyo_creacion = Integer.parseInt(this.jSpinnerAnyoCreacion.getValue().toString());
        String genero = GeneroMusical.valueOf(this.jComboBoxGenero.getSelectedItem().toString().toUpperCase()).toString();
        String nombreAutor = this.jComboBoxAutores.getSelectedItem().toString();

        Autor autor = AutorController.obtener(nombreAutor);

        if (!titulo.isEmpty() && duracion != 0 && anyo_creacion > 0 && autor != null) {
            Cancion nuevaCancion = new Cancion(titulo, duracion, anyo_creacion, genero, autor);

            boolean resultado = CancionController.guardar(nuevaCancion);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "Canción almacenada correctamente en la base de datos DB4O", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            this.limpiarFormularioCancion();
            this.listarCanciones();
        } else {
            JOptionPane.showMessageDialog(null, "Revisa la información introducida para almacenar la canción", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarCancionActionPerformed

    private void jMenuItemEliminarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemEliminarAutorMousePressed
        if (hayAutorSeleccionado()) {
            int filaSeleccionada = jTableAutores.getSelectedRow();

            DefaultTableModel modelo = (DefaultTableModel) jTableAutores.getModel();
            String nombreAutor = modelo.getValueAt(filaSeleccionada, 0).toString(); // Obtener el nombre del autor

            boolean resultado = AutorController.eliminar(nombreAutor);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "Autor eliminado correctamente de la base de datos DB4O", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "El autor seleccionado no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.listarAutores();
        } else {
            JOptionPane.showMessageDialog(this, "Primero, debes seleccionar un autor", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemEliminarAutorMousePressed

    private void jMenuItemModificarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemModificarAutorMousePressed
        // TODO add your handling code here:
        if (hayAutorSeleccionado()) {
            int filaSeleccionada = jTableAutores.getSelectedRow();

            DefaultTableModel modelo = (DefaultTableModel) jTableAutores.getModel();
            String nombreAutor = modelo.getValueAt(filaSeleccionada, 0).toString(); // Obtener el nombre
            String nacionalidad = modelo.getValueAt(filaSeleccionada, 1).toString(); // Obtener el nacionalidad
            String paisResidencia = modelo.getValueAt(filaSeleccionada, 2).toString(); // Obtener el país de residencia
            int anyoNacimiento = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 3).toString()); // Obtener el año de nacimiento
            int ingresosAnuales = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 4).toString()); // Obtener los ingresos anuales

            this.jTextFieldNombre.setText(nombreAutor);
            this.jTextFieldNacionalidad.setText(nacionalidad);
            this.jTextFieldPais.setText(paisResidencia);
            this.jSpinnerAnyoNacimiento.setValue(anyoNacimiento);
            this.jSpinnerIngresosAnuales.setValue(ingresosAnuales);

        } else {
            JOptionPane.showMessageDialog(this, "Primero, debes seleccionar un autor", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemModificarAutorMousePressed

    private void jMenuItemModificarCancionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemModificarCancionMousePressed
        // TODO add your handling code here:
        if (hayCancionSeleccionada()) {
            int filaSeleccionada = jTableCanciones.getSelectedRow();

            DefaultTableModel modelo = (DefaultTableModel) jTableCanciones.getModel();
            String id = modelo.getValueAt(filaSeleccionada, 0).toString(); // Obtener el identificador
            String titulo = modelo.getValueAt(filaSeleccionada, 1).toString(); // Obtener el título
            int duracion = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 2).toString()); // Obtener la duracion
            int anyoDeCreacion = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 3).toString()); // Obtener el año de creación
            String genero = modelo.getValueAt(filaSeleccionada, 4).toString(); // Obtener el género
            String nombreAutor = modelo.getValueAt(filaSeleccionada, 5).toString(); // Obtener el nombre del autor de la canción

            this.jTextFieldTitulo.setText(titulo);
            this.jSpinnerDuracion.setValue(duracion);
            this.jSpinnerAnyoCreacion.setValue(anyoDeCreacion);
            
            // Seleccionar el género en el JComboBox
            for (int i = 0; i < jComboBoxGenero.getItemCount(); i++) {
                if (jComboBoxGenero.getItemAt(i).equalsIgnoreCase(genero)) {
                    jComboBoxGenero.setSelectedIndex(i);
                    break;
                }
            }

            // Seleccionar el autor en el JComboBox
            boolean autorEncontrado = false;
            for (int i = 0; i < jComboBoxAutores.getItemCount(); i++) {
                if (jComboBoxAutores.getItemAt(i).equalsIgnoreCase(nombreAutor)) {
                    jComboBoxAutores.setSelectedIndex(i);
                    autorEncontrado = true;
                    break;
                }
            }

            // Si el autor no se encuentra en el JComboBox, agregarlo
            if (!autorEncontrado) {
                jComboBoxAutores.setSelectedItem(nombreAutor);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Primero, debes seleccionar una canción", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemModificarCancionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void listarAutores() {
        List<Autor> autores = AutorController.obtenerTodos();

        // Obtener el modelo de la tabla y limpiarlo antes de agregar nuevos datos
        DefaultTableModel modelo = (DefaultTableModel) jTableAutores.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de actualizarla

        // Recorrer la lista de canciones y agregarlas a la tabla
        for (Autor autor : autores) {
            Object[] fila = {
                autor.getNombre(), // Columna 1: Nombre
                autor.getNacionalidad(), // Columna 2: Nacionalidad
                autor.getPaisResidencia(), // Columna 3: País de residencia
                autor.getAnyoDeNacimiento(), // Columna 4: Año de nacimiento
                autor.getIngresosAnuales()// Columna 5: Ingresos anuales
            };
            modelo.addRow(fila); // Agregar la fila a la tabla
        }

        // actualizo la combobox de autores a elegir de las canciones
        this.rellenarComboBoxAutores();
    }

    private void listarCanciones() {
        List<Cancion> canciones = CancionController.obtenerTodas();

        // Obtener el modelo de la tabla y limpiarlo antes de agregar nuevos datos
        DefaultTableModel modelo = (DefaultTableModel) jTableCanciones.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de actualizarla

        // Recorrer la lista de canciones y agregarlas a la tabla
        for (Cancion cancion : canciones) {
            Object[] fila = {
                cancion.getIdentificador(), // Columna 1: ID
                cancion.getTitulo(), // Columna 2: Título
                cancion.getDuracion(), // Columna 3: Duración
                cancion.getAnyoCreacion(), // Columna 4: Año de creación
                cancion.getGenero().toString(), // Columna 5: Género
                cancion.getAutor().getNombre() // Columna 6: Autor
            };
            modelo.addRow(fila); // Agregar la fila a la tabla
        }
    }

    private boolean hayCancionSeleccionada() {
        return this.jTableCanciones.getSelectedRow() != -1;
    }

    private boolean hayAutorSeleccionado() {
        return this.jTableAutores.getSelectedRow() != -1;
    }

    private void rellenarComboBoxAutores() {
        // Obtener la lista de autores desde la base de datos
        List<Autor> autores = AutorController.obtenerTodos();

        // Limpiar el JComboBox antes de agregar nuevos datos
        jComboBoxAutores.removeAllItems();

        // Verificar si hay autores en la lista
        if (autores.isEmpty()) {
            jComboBoxAutores.addItem("No hay autores disponibles");
        } else {
            for (Autor autor : autores) {
                jComboBoxAutores.addItem(autor.getNombre()); // Agregar cada nombre al ComboBox
            }
        }

    }

    private void inicializarFormulario() {
        // Seteo de valor de título y posición del frame
        this.setTitle("Podadera's Songs Vault");
        this.setLocationRelativeTo(null);

        // Inicializacion de valores de los spinners
        this.jSpinnerAnyoNacimiento.setValue(2000);
        this.jSpinnerAnyoCreacion.setValue(2000);

        // Mostrar todas las canciones
        this.listarCanciones();

        // Mostrar todos los autores
        this.listarAutores();

        // Cargar autores en combobox autores de las canciones
        this.rellenarComboBoxAutores();

        // Evento para cerrar la base de datos al cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ConexionDB4O.cerrar();
            }
        });
    }

    private void limpiarFormularioAutor() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldNacionalidad.setText("");
        this.jTextFieldPais.setText("");
        this.jSpinnerAnyoNacimiento.setValue(2000);
        this.jSpinnerIngresosAnuales.setValue(0);
    }

    private void limpiarFormularioCancion() {
        this.jTextFieldTitulo.setText("");
        this.jSpinnerDuracion.setValue(0);
        this.jSpinnerAnyoCreacion.setValue(2000);
        this.jComboBoxGenero.setSelectedIndex(0);
        this.jComboBoxAutores.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAumentarSalario;
    private javax.swing.JButton jButtonConsultarAutoresEnRango;
    private javax.swing.JButton jButtonConsultarAutoresEnRango1;
    private javax.swing.JButton jButtonConsultarCancionesDeAutor;
    private javax.swing.JButton jButtonConsultarCancionesOrdenadas;
    private javax.swing.JButton jButtonConsultarTodasCanciones;
    private javax.swing.JButton jButtonGuardarAutor;
    private javax.swing.JButton jButtonGuardarCancion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxAutores;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemEliminarAutor;
    private javax.swing.JMenuItem jMenuItemEliminarCancion;
    private javax.swing.JMenuItem jMenuItemModificarAutor;
    private javax.swing.JMenuItem jMenuItemModificarCancion;
    private javax.swing.JPanel jPanelAutores;
    private javax.swing.JPanel jPanelCanciones;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPopupMenu jPopupMenuAutores;
    private javax.swing.JPopupMenu jPopupMenuCanciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAnyoCreacion;
    private javax.swing.JSpinner jSpinnerAnyoNacimiento;
    private javax.swing.JSpinner jSpinnerDuracion;
    private javax.swing.JSpinner jSpinnerIngresosAnuales;
    private javax.swing.JTable jTableAutores;
    private javax.swing.JTable jTableCanciones;
    private javax.swing.JTextField jTextFieldBusquedaAutor;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPorcentajeAumento;
    private javax.swing.JTextField jTextFieldSalarioFinal;
    private javax.swing.JTextField jTextFieldSalarioInicial;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
