/**
 * Crea un programa en Java, que permita leer el fichero llamado "datosContacto.dat"
 * del ejercicio anterior del directorio datos y permita mostrarlos por pantalla
 * de forma secuencial, también habría que contar el número de registros que
 * existen en el fichero. Se entiende por un registro cada línea creada por cada
 * uno de los campos. Deberás documentar bien tu código así como realizar el
 * adecuado manejo de las posibles excepciones.
 */
package ejercicio3;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase Ejercicio3 para la resolución del ejercicio 3.
 * <p>
 * Esta clase implementa una interfaz gráfica en Java Swing que permite leer la
 * informacion de un archivo de datos binario y mostrarla en una tabla</p>
 *
 * <p>
 * La ventana se centra automáticamente en la pantalla y tiene como título
 * "Ejercicio 3".</p>
 *
 * @author Andrés Samuel Podadera González
 * @version 1.0
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * crea un nuevo formulario Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
        // centrar el formulario en la pantalla
        this.setLocationRelativeTo(null);
        // colocar titulo a la ventana
        this.setTitle("Ejercicio 3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButtonCargarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelNumeroRegistros = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Ejercicio 3 - Programa lector de archivos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTableDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableDatos.setForeground(new java.awt.Color(0, 0, 102));
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Email"
            }
        ));
        jTableDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableDatos);

        jButtonCargarDatos.setBackground(new java.awt.Color(0, 102, 255));
        jButtonCargarDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCargarDatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCargarDatos.setText("Cargar datos");
        jButtonCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCargarDatosMouseClicked(evt);
            }
        });
        jButtonCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDatosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Pulsa el botón para cargar los datos:");

        jLabelNumeroRegistros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroRegistros.setForeground(new java.awt.Color(0, 51, 51));
        jLabelNumeroRegistros.setText("Número de registros encontrados:");

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(jButtonCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNumeroRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroRegistros)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCargarDatosActionPerformed

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonCargarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCargarDatosMouseClicked
        File fichero = new File("datosContacto.dat");
        // comprobar si existe el archivo
        if (!fichero.exists()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error en el proceso de lectura, el archivo 'datosContacto.dat' no existe", // mensaje a mostrar
                    "Error", // título de la ventana del diálogo
                    JOptionPane.ERROR_MESSAGE // tipo de mensaje
            );
            return;
        }
        //contador de registros
        int numeroRegistros = 0;
        // vincular un DefaultTableModel a la JTable existente
        DefaultTableModel tableModel = (DefaultTableModel) jTableDatos.getModel();

        // crear una lista para almacenar los registros actuales de la tabla
        ArrayList<String> registrosExistentes = new ArrayList<>();
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String nombre = (String) tableModel.getValueAt(i, 0);
            String apellidos = (String) tableModel.getValueAt(i, 1);
            String email = (String) tableModel.getValueAt(i, 2);
            registrosExistentes.add(nombre + apellidos + email);
        }

        String nombre;
        String apellidos;
        String email;
        FileInputStream fileInputStream = null;
        DataInputStream dataInputStream = null;
        // leer el archivo
        try {
            fileInputStream = new FileInputStream(fichero);
            dataInputStream = new DataInputStream(fileInputStream);
            // recorro los datos del archivo
            while (dataInputStream.available() > 0) {
                nombre = dataInputStream.readUTF();
                apellidos = dataInputStream.readUTF();
                email = dataInputStream.readUTF();

                // Crear una cadena única para verificar duplicados
                String registro = nombre + apellidos + email;
                // verificar si el registro ya existe
                if (!registrosExistentes.contains(registro)) {
                    // agregar el registro si no existe en la tabla
                    tableModel.addRow(new String[]{nombre, apellidos, email});
                }
                numeroRegistros++;
            }
            // mostrar el numero de registros leidos
            this.jLabelNumeroRegistros.setText("Número de registros encontrados: " + numeroRegistros);
            // mostrar aviso al usuario que los datos se leyeron correctamente
            JOptionPane.showMessageDialog(
                    this,
                    "Datos cargados correctamente desde 'datosContacto.dat'", // mensaje a mostrar
                    "Información", // título de la ventana del diálogo
                    JOptionPane.INFORMATION_MESSAGE // tipo de mensaje
            );
        } catch (FileNotFoundException ex) {
            System.out.println("Archivo no encontrado");
        } catch (IOException ex) {
            System.err.println("Error en la operación de entrada/salida");
        } finally {
            // cerrar los flujos en bloques try-catch individuales
            try {
                if (dataInputStream != null) {
                    dataInputStream.close();
                }
            } catch (IOException ex) {
                System.out.println("Error al cerrar DataOutputStream");
            }
            try {
                if (fileInputStream != null) {
                    fileInputStream.close();
                }
            } catch (IOException ex) {
                System.out.println("Error al cerrar FileOutputStream");
            }
        }
    }//GEN-LAST:event_jButtonCargarDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNumeroRegistros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    // End of variables declaration//GEN-END:variables
}
