package vistas;

import controladores.TallerController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Reparacion;
import modelos.Vehiculo;
import org.basex.core.Context;
import org.basex.query.QueryException;

/**
 * Clase del formulario principal del programa, muestra listado de vehículos,
 * reparaciones y varios botones que permiten la funcionalidad que pide la tarea
 *
 * @author andres
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private static Context contexto = null;

    /**
     * Creates new form JFramePrincipal
     *
     * @param contexto
     */
    public JFramePrincipal(Context contexto) throws QueryException {
        initComponents();
        JFramePrincipal.contexto = contexto;
        //rellenarTablaVehiculos();
        //rellenarTablaReparaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloTarea = new javax.swing.JLabel();
        jLabelNombreAutor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelVehiculo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jLabelRparaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReparaciones = new javax.swing.JTable();
        jButtonListarVehiculos = new javax.swing.JButton();
        jButtonListarReparaciones = new javax.swing.JButton();
        jButtonConsultarVehiculosFecha2024 = new javax.swing.JButton();
        jButtonConsultarVehiculosKm = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaResultados = new javax.swing.JTextArea();
        jButtonConsultarPropietariosGolf = new javax.swing.JButton();
        jButtonConsultarMecanicos = new javax.swing.JButton();
        jButtonModificarNodoKm = new javax.swing.JButton();
        jButtonInsertarReparacion = new javax.swing.JButton();
        jButtonGuardarColecciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonModificarCantidadKm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloTarea.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTituloTarea.setText("Acceso a datos - TAREA 5 - DAM ");

        jLabelNombreAutor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombreAutor.setText("Andrés Samuel Podadera González ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabelNombreAutor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabelTituloTarea)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTituloTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombreAutor)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabelVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelVehiculo.setText("Vehículos:");

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Año de fabricación", "Propietario", "Marca", "Modelo", "Kilometraje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVehiculos);
        if (jTableVehiculos.getColumnModel().getColumnCount() > 0) {
            jTableVehiculos.getColumnModel().getColumn(2).setMinWidth(150);
            jTableVehiculos.getColumnModel().getColumn(5).setMinWidth(20);
        }

        jLabelRparaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelRparaciones.setText("Reparaciones:");

        jTableReparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Fecha Inicio", "Fecha Fin", "Nombre Mecánico", "Apellidos Mecánico", "Teléfono Mecánico"
            }
        ));
        jScrollPane2.setViewportView(jTableReparaciones);

        jButtonListarVehiculos.setText("Consultar Vehiculos");
        jButtonListarVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonListarVehiculosMouseClicked(evt);
            }
        });

        jButtonListarReparaciones.setText("Consultar Reparaciones");
        jButtonListarReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonListarReparacionesMouseClicked(evt);
            }
        });

        jButtonConsultarVehiculosFecha2024.setText("Consultar Vehiculos Del 2024");
        jButtonConsultarVehiculosFecha2024.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarVehiculosFecha2024MouseClicked(evt);
            }
        });

        jButtonConsultarVehiculosKm.setText("Consultar Vehiculos con mas de 75000 KM");
        jButtonConsultarVehiculosKm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarVehiculosKmMouseClicked(evt);
            }
        });

        jTextAreaResultados.setColumns(20);
        jTextAreaResultados.setRows(5);
        jScrollPane3.setViewportView(jTextAreaResultados);

        jButtonConsultarPropietariosGolf.setText("Consultar Propietarios con Golf");
        jButtonConsultarPropietariosGolf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarPropietariosGolfMouseClicked(evt);
            }
        });

        jButtonConsultarMecanicos.setText("Consultar Mecanicos");
        jButtonConsultarMecanicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarMecanicosMouseClicked(evt);
            }
        });

        jButtonModificarNodoKm.setText("Modificar Nodo Kilometros");
        jButtonModificarNodoKm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarNodoKmMouseClicked(evt);
            }
        });

        jButtonInsertarReparacion.setText("Insertar Nueva Reparacion");
        jButtonInsertarReparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInsertarReparacionMouseClicked(evt);
            }
        });

        jButtonGuardarColecciones.setText("Guardar Colecciones en Archivos");
        jButtonGuardarColecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarColeccionesMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Resultados:");

        jButtonModificarCantidadKm.setText("Modificar KM al 6666FFF");
        jButtonModificarCantidadKm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarCantidadKmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRparaciones, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jButtonListarVehiculos))
                                    .addComponent(jButtonConsultarVehiculosFecha2024)
                                    .addComponent(jButtonConsultarVehiculosKm)
                                    .addComponent(jButtonConsultarPropietariosGolf)
                                    .addComponent(jButtonConsultarMecanicos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModificarNodoKm)
                                    .addComponent(jButtonModificarCantidadKm)
                                    .addComponent(jButtonInsertarReparacion))
                                .addGap(34, 34, 34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jButtonGuardarColecciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonListarReparaciones)
                                .addGap(117, 117, 117)))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabelRparaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarReparaciones)
                    .addComponent(jButtonListarVehiculos))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonModificarCantidadKm)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModificarNodoKm)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInsertarReparacion)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsultarVehiculosFecha2024)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsultarVehiculosKm)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsultarPropietariosGolf)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsultarMecanicos)))
                        .addComponent(jButtonGuardarColecciones)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarColeccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarColeccionesMouseClicked
        // EJERCICIO 1: Procesar y guardar colecciones
        boolean resultado = TallerController.guardarVehiculos(contexto)
                && TallerController.guardarReparaciones(contexto)
                && TallerController.guardarMarcas(contexto);

        if (resultado) {
            JOptionPane.showMessageDialog(null, "✅ Guardado exitoso de los vehículos, reparaciones y marcas.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "❌ Error guardar las colecciones.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarColeccionesMouseClicked

    private void jButtonConsultarMecanicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarMecanicosMouseClicked
        // TODO add your handling code here:
        this.mostrarTodosMecanicos();
    }//GEN-LAST:event_jButtonConsultarMecanicosMouseClicked

    private void jButtonConsultarPropietariosGolfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarPropietariosGolfMouseClicked
        // TODO add your handling code here:
        this.mostrarPropietariosConGolf();
    }//GEN-LAST:event_jButtonConsultarPropietariosGolfMouseClicked

    private void jButtonConsultarVehiculosKmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarVehiculosKmMouseClicked
        // TODO add your handling code here:
        this.mostrarVehiculosConKilometros();
    }//GEN-LAST:event_jButtonConsultarVehiculosKmMouseClicked

    private void jButtonConsultarVehiculosFecha2024MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarVehiculosFecha2024MouseClicked
        // TODO add your handling code here:
        this.mostrarVehiculos2024();
    }//GEN-LAST:event_jButtonConsultarVehiculosFecha2024MouseClicked

    private void jButtonListarReparacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListarReparacionesMouseClicked
        // TODO add your handling code here:
        this.rellenarTablaReparaciones();
    }//GEN-LAST:event_jButtonListarReparacionesMouseClicked

    private void jButtonListarVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListarVehiculosMouseClicked
        // TODO add your handling code here:
        this.rellenarTablaVehiculos();
    }//GEN-LAST:event_jButtonListarVehiculosMouseClicked

    private void jButtonModificarCantidadKmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarCantidadKmMouseClicked
        // TODO add your handling code here:
        this.modificarKilometrosDe6666FFF();
    }//GEN-LAST:event_jButtonModificarCantidadKmMouseClicked

    private void jButtonModificarNodoKmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarNodoKmMouseClicked
        // TODO add your handling code here:
        this.modificarNodoKilometrosAKm();
        this.modificarNodoKmAKilometros();
    }//GEN-LAST:event_jButtonModificarNodoKmMouseClicked

    private void jButtonInsertarReparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInsertarReparacionMouseClicked
        // TODO add your handling code here:
        this.insertarNuevaReparacion();
    }//GEN-LAST:event_jButtonInsertarReparacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JFramePrincipal(contexto).setVisible(true);
            } catch (QueryException ex) {
                Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private void rellenarTablaVehiculos() {
        List<Vehiculo> vehiculos = TallerController.obtenerTodosVehiculos(contexto);

        DefaultTableModel model = (DefaultTableModel) jTableVehiculos.getModel();

        // Eliminar todas las filas existentes
        model.setRowCount(0);

        for (Vehiculo v : vehiculos) {
            model.addRow(new Object[]{
                v.getMatricula(),
                v.getAnyoFabricacion(),
                v.getPropietario().getNombre() + " " + v.getPropietario().getApellidos(),
                v.getMarca(),
                v.getModelo(),
                v.getKilometraje()
            });
        }
    }

    private void rellenarTablaReparaciones() {
        List<Reparacion> reparaciones = TallerController.obtenerTodasReparaciones(contexto);

        DefaultTableModel model = (DefaultTableModel) jTableReparaciones.getModel();

        // Eliminar todas las filas existentes
        model.setRowCount(0);

        for (Reparacion reparacion : reparaciones) {
            model.addRow(new Object[]{
                reparacion.getMatricula(),
                reparacion.getInicio().toString(),
                reparacion.getFin() != null ? reparacion.getFin() : "Sin Terminar",
                reparacion.getMecanico().getNombre(),
                reparacion.getMecanico().getApellidos(),
                reparacion.getMecanico().getTelefono()
            });
        }

    }

    private void mostrarVehiculos2024() {
        String vehiculos2024 = TallerController.obtenerVehiculos2024(contexto);

        this.jTextAreaResultados.setText(vehiculos2024);

    }

    private void mostrarVehiculosConKilometros() {
        String vehiculosCon75000 = TallerController.obtenerVehiculosCon75000(contexto);

        this.jTextAreaResultados.setText(vehiculosCon75000);
    }

    private void mostrarPropietariosConGolf() {
        String propietariosConGolf = TallerController.obtenerPropietariosConGolf(contexto);

        this.jTextAreaResultados.setText(propietariosConGolf);
    }

    private void mostrarTodosMecanicos() {
        String mecanicos = TallerController.obtenerMecanicos(contexto);

        this.jTextAreaResultados.setText(mecanicos);
    }

    private void modificarKilometrosDe6666FFF() {
        boolean resultado = TallerController.modificarKilometrosDe6666FFF(contexto);

        if (resultado) {
            this.rellenarTablaVehiculos();

            JOptionPane.showMessageDialog(null, "✅ Modificación de los kilómetros del vehículo con matrícula 6666FFF realizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "❌ Error en la modificación de los kilómetros del vehículo con matrícula 6666FFF", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void modificarNodoKilometrosAKm() {
        String nodosModificados = TallerController.modificarNodoKilometrosAKm(contexto);

        this.jTextAreaResultados.setText(nodosModificados);
    }

    private void modificarNodoKmAKilometros() {
        TallerController.modificarNodoKmAKilometros(contexto);
    }

    private void insertarNuevaReparacion() {
        boolean resultado = TallerController.insertarNuevaReparacion(contexto);

        if (resultado) {
            this.rellenarTablaReparaciones();

            JOptionPane.showMessageDialog(null, "✅ Reparación insertada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "❌ Error en la inserción de una reparación.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarMecanicos;
    private javax.swing.JButton jButtonConsultarPropietariosGolf;
    private javax.swing.JButton jButtonConsultarVehiculosFecha2024;
    private javax.swing.JButton jButtonConsultarVehiculosKm;
    private javax.swing.JButton jButtonGuardarColecciones;
    private javax.swing.JButton jButtonInsertarReparacion;
    private javax.swing.JButton jButtonListarReparaciones;
    private javax.swing.JButton jButtonListarVehiculos;
    private javax.swing.JButton jButtonModificarCantidadKm;
    private javax.swing.JButton jButtonModificarNodoKm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombreAutor;
    private javax.swing.JLabel jLabelRparaciones;
    private javax.swing.JLabel jLabelTituloTarea;
    private javax.swing.JLabel jLabelVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableReparaciones;
    private javax.swing.JTable jTableVehiculos;
    private javax.swing.JTextArea jTextAreaResultados;
    // End of variables declaration//GEN-END:variables

}
