package model.entity;
// Generated 10-dic-2024 19:24:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String nif;
     private Universidad universidad;
     private String nombre;
     private String apellidos;
     private Date fechaNacimiento;
     private String direccion;
     private String provincia;
     private float importeMatricula;
     private boolean becado;

    public Estudiante() {
    }

    public Estudiante(String nif, Universidad universidad, String nombre, String apellidos, Date fechaNacimiento, String direccion, String provincia, float importeMatricula, boolean becado) {
       this.nif = nif;
       this.universidad = universidad;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.provincia = provincia;
       this.importeMatricula = importeMatricula;
       this.becado = becado;
    }
   
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public float getImporteMatricula() {
        return this.importeMatricula;
    }
    
    public void setImporteMatricula(float importeMatricula) {
        this.importeMatricula = importeMatricula;
    }
    public boolean isBecado() {
        return this.becado;
    }
    
    public void setBecado(boolean becado) {
        this.becado = becado;
    }




}


