package view;

/**
 *
 * @author ANDRES SAMUEL PODADERA GONZALEZ
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        setTitle("Acceso a Datos: Tarea 3 - Andrés Samuel Podadera González");
        setSize(950, 700);
        setDefaultCloseOperation(javax.swing.JDialog.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionMenuAcciones = new javax.swing.JMenu();
        menuItemApartadosABC = new javax.swing.JMenuItem();
        menuItemApartadoDEF = new javax.swing.JMenuItem();
        opcionMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/uni.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        labelTitulo.setText("Universidades y Estudiantes");

        opcionMenuAcciones.setText("Acciones");
        opcionMenuAcciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        menuItemApartadosABC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemApartadosABC.setText("Universidades y Estudiantes (Apartados A, B y C)");
        menuItemApartadosABC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemApartadosABCMousePressed(evt);
            }
        });
        opcionMenuAcciones.add(menuItemApartadosABC);

        menuItemApartadoDEF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemApartadoDEF.setText("Operaciones Complejas (Apartados D, E y F)");
        menuItemApartadoDEF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemApartadoDEFMousePressed(evt);
            }
        });
        opcionMenuAcciones.add(menuItemApartadoDEF);

        jMenuBar1.add(opcionMenuAcciones);

        opcionMenuSalir.setText("Salir");
        opcionMenuSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        opcionMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(opcionMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(327, 327, 327))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionMenuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_opcionMenuSalirMouseClicked

    private void menuItemApartadosABCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemApartadosABCMousePressed
        UniversidadDialog universidadDialog= new UniversidadDialog(this, rootPaneCheckingEnabled);
        universidadDialog.setVisible(true);
    }//GEN-LAST:event_menuItemApartadosABCMousePressed

    private void menuItemApartadoDEFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemApartadoDEFMousePressed
        OperacionesComplejasDialog operacionesComplejasDialog= new OperacionesComplejasDialog(this, rootPaneCheckingEnabled);
        operacionesComplejasDialog.setVisible(true);
    }//GEN-LAST:event_menuItemApartadoDEFMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenuItem menuItemApartadoDEF;
    private javax.swing.JMenuItem menuItemApartadosABC;
    private javax.swing.JMenu opcionMenuAcciones;
    private javax.swing.JMenu opcionMenuSalir;
    // End of variables declaration//GEN-END:variables
}
